// 语法版本是protobuf3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: server.proto

// service 的 root path,客户端的protocol文件的package 的此值和server端的要一致，不然路径会匹配不上

package esdeath_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckStatus int32

const (
	AckStatus_ACK       AckStatus = 0
	AckStatus_RECONSUME AckStatus = 1
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "ACK",
		1: "RECONSUME",
	}
	AckStatus_value = map[string]int32{
		"ACK":       0,
		"RECONSUME": 1,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[0].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[0]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

type ResultStatus int32

const (
	ResultStatus_SUCCESS            ResultStatus = 0
	ResultStatus_FAIL               ResultStatus = 1
	ResultStatus_REFUSE_BY_FOLLOWER ResultStatus = 2
	ResultStatus_NO_MESSAGE         ResultStatus = 3
)

// Enum value maps for ResultStatus.
var (
	ResultStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL",
		2: "REFUSE_BY_FOLLOWER",
		3: "NO_MESSAGE",
	}
	ResultStatus_value = map[string]int32{
		"SUCCESS":            0,
		"FAIL":               1,
		"REFUSE_BY_FOLLOWER": 2,
		"NO_MESSAGE":         3,
	}
)

func (x ResultStatus) Enum() *ResultStatus {
	p := new(ResultStatus)
	*p = x
	return p
}

func (x ResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[1].Descriptor()
}

func (ResultStatus) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[1]
}

func (x ResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultStatus.Descriptor instead.
func (ResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

// 角色
type Role int32

const (
	Role_LEADER   Role = 0
	Role_FOLLOWER Role = 1
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "LEADER",
		1: "FOLLOWER",
	}
	Role_value = map[string]int32{
		"LEADER":   0,
		"FOLLOWER": 1,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[2].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[2]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

// 取消延迟消息请求
type DelayMsgCancel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId string `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
}

func (x *DelayMsgCancel) Reset() {
	*x = DelayMsgCancel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelayMsgCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayMsgCancel) ProtoMessage() {}

func (x *DelayMsgCancel) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayMsgCancel.ProtoReflect.Descriptor instead.
func (*DelayMsgCancel) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *DelayMsgCancel) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

// 新增延迟消息请求
type DelayMsgAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DelayTime int64  `protobuf:"varint,1,opt,name=delayTime,proto3" json:"delayTime,omitempty"`
	Topic     string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Tag       string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	MsgId     string `protobuf:"bytes,4,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Payload   string `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *DelayMsgAdd) Reset() {
	*x = DelayMsgAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelayMsgAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayMsgAdd) ProtoMessage() {}

func (x *DelayMsgAdd) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayMsgAdd.ProtoReflect.Descriptor instead.
func (*DelayMsgAdd) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *DelayMsgAdd) GetDelayTime() int64 {
	if x != nil {
		return x.DelayTime
	}
	return 0
}

func (x *DelayMsgAdd) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DelayMsgAdd) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *DelayMsgAdd) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *DelayMsgAdd) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// 拉取延迟消息请求
type DelayMsgPull struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic         string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	ConsumerGroup string `protobuf:"bytes,2,opt,name=consumerGroup,proto3" json:"consumerGroup,omitempty"`
}

func (x *DelayMsgPull) Reset() {
	*x = DelayMsgPull{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelayMsgPull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayMsgPull) ProtoMessage() {}

func (x *DelayMsgPull) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayMsgPull.ProtoReflect.Descriptor instead.
func (*DelayMsgPull) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *DelayMsgPull) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DelayMsgPull) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

// 消息消费请求
type DelayMsgAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status        AckStatus `protobuf:"varint,1,opt,name=status,proto3,enum=esdeath.AckStatus" json:"status,omitempty"`
	Topic         string    `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	ConsumerGroup string    `protobuf:"bytes,3,opt,name=consumerGroup,proto3" json:"consumerGroup,omitempty"`
	MsgId         string    `protobuf:"bytes,4,opt,name=msgId,proto3" json:"msgId,omitempty"`
}

func (x *DelayMsgAck) Reset() {
	*x = DelayMsgAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelayMsgAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayMsgAck) ProtoMessage() {}

func (x *DelayMsgAck) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayMsgAck.ProtoReflect.Descriptor instead.
func (*DelayMsgAck) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *DelayMsgAck) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_ACK
}

func (x *DelayMsgAck) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DelayMsgAck) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *DelayMsgAck) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type BaseResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ResultStatus `protobuf:"varint,1,opt,name=status,proto3,enum=esdeath.ResultStatus" json:"status,omitempty"`
	Desc   string       `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *BaseResult) Reset() {
	*x = BaseResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResult) ProtoMessage() {}

func (x *BaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResult.ProtoReflect.Descriptor instead.
func (*BaseResult) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *BaseResult) GetStatus() ResultStatus {
	if x != nil {
		return x.Status
	}
	return ResultStatus_SUCCESS
}

func (x *BaseResult) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

// 新增延迟消息响应
type AddDelayMsgResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResult *BaseResult `protobuf:"bytes,1,opt,name=baseResult,proto3" json:"baseResult,omitempty"`
	MsgId      string      `protobuf:"bytes,2,opt,name=msgId,proto3" json:"msgId,omitempty"`
}

func (x *AddDelayMsgResult) Reset() {
	*x = AddDelayMsgResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDelayMsgResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDelayMsgResult) ProtoMessage() {}

func (x *AddDelayMsgResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDelayMsgResult.ProtoReflect.Descriptor instead.
func (*AddDelayMsgResult) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *AddDelayMsgResult) GetBaseResult() *BaseResult {
	if x != nil {
		return x.BaseResult
	}
	return nil
}

func (x *AddDelayMsgResult) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

// 拉取延迟消息响应
type PullDelayMsgResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResult *BaseResult `protobuf:"bytes,1,opt,name=baseResult,proto3" json:"baseResult,omitempty"`
	Topic      string      `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Tag        string      `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	MsgId      string      `protobuf:"bytes,4,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Payload    string      `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *PullDelayMsgResult) Reset() {
	*x = PullDelayMsgResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullDelayMsgResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullDelayMsgResult) ProtoMessage() {}

func (x *PullDelayMsgResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullDelayMsgResult.ProtoReflect.Descriptor instead.
func (*PullDelayMsgResult) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *PullDelayMsgResult) GetBaseResult() *BaseResult {
	if x != nil {
		return x.BaseResult
	}
	return nil
}

func (x *PullDelayMsgResult) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PullDelayMsgResult) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *PullDelayMsgResult) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *PullDelayMsgResult) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// 取消延迟消息响应
type CancelDelayMsgResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResult *BaseResult `protobuf:"bytes,1,opt,name=baseResult,proto3" json:"baseResult,omitempty"`
}

func (x *CancelDelayMsgResult) Reset() {
	*x = CancelDelayMsgResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelDelayMsgResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDelayMsgResult) ProtoMessage() {}

func (x *CancelDelayMsgResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDelayMsgResult.ProtoReflect.Descriptor instead.
func (*CancelDelayMsgResult) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *CancelDelayMsgResult) GetBaseResult() *BaseResult {
	if x != nil {
		return x.BaseResult
	}
	return nil
}

// ACK延迟消息响应
type AckDelayMsgResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResult *BaseResult `protobuf:"bytes,1,opt,name=baseResult,proto3" json:"baseResult,omitempty"`
}

func (x *AckDelayMsgResult) Reset() {
	*x = AckDelayMsgResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckDelayMsgResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckDelayMsgResult) ProtoMessage() {}

func (x *AckDelayMsgResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckDelayMsgResult.ProtoReflect.Descriptor instead.
func (*AckDelayMsgResult) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *AckDelayMsgResult) GetBaseResult() *BaseResult {
	if x != nil {
		return x.BaseResult
	}
	return nil
}

type RoleResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResult *BaseResult `protobuf:"bytes,1,opt,name=baseResult,proto3" json:"baseResult,omitempty"`
	Role       Role        `protobuf:"varint,2,opt,name=role,proto3,enum=esdeath.Role" json:"role,omitempty"`
}

func (x *RoleResult) Reset() {
	*x = RoleResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResult) ProtoMessage() {}

func (x *RoleResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResult.ProtoReflect.Descriptor instead.
func (*RoleResult) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *RoleResult) GetBaseResult() *BaseResult {
	if x != nil {
		return x.BaseResult
	}
	return nil
}

func (x *RoleResult) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_LEADER
}

var File_server_proto protoreflect.FileDescriptor

var file_server_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x65, 0x73, 0x64, 0x65, 0x61, 0x74, 0x68, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x83, 0x01, 0x0a,
	0x0b, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x41, 0x64, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x64, 0x65, 0x6c, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74,
	0x61, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x4a, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x50, 0x75,
	0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x8b,
	0x01, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x41, 0x63, 0x6b, 0x12, 0x2a,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x65, 0x73, 0x64, 0x65, 0x61, 0x74, 0x68, 0x2e, 0x41, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x4f, 0x0a, 0x0a,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x65, 0x73, 0x64,
	0x65, 0x61, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x5e, 0x0a,
	0x11, 0x41, 0x64, 0x64, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x65, 0x73, 0x64, 0x65, 0x61, 0x74, 0x68,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0a, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0xa1, 0x01,
	0x0a, 0x12, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x65, 0x73, 0x64, 0x65, 0x61,
	0x74, 0x68, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0a, 0x62,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x4b, 0x0a, 0x14, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x44, 0x65, 0x6c, 0x61, 0x79,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x65, 0x73, 0x64, 0x65, 0x61, 0x74, 0x68, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x48,
	0x0a, 0x11, 0x41, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x65, 0x73, 0x64, 0x65, 0x61, 0x74,
	0x68, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0a, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x64, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x65, 0x73, 0x64,
	0x65, 0x61, 0x74, 0x68, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x0a, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x65, 0x73, 0x64, 0x65,
	0x61, 0x74, 0x68, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x2a, 0x23,
	0x0a, 0x09, 0x41, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x43, 0x4b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x43, 0x4f, 0x4e, 0x53, 0x55, 0x4d,
	0x45, 0x10, 0x01, 0x2a, 0x4d, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45,
	0x46, 0x55, 0x53, 0x45, 0x5f, 0x42, 0x59, 0x5f, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57, 0x45, 0x52,
	0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x10, 0x03, 0x2a, 0x20, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x45,
	0x41, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57,
	0x45, 0x52, 0x10, 0x01, 0x32, 0xd1, 0x02, 0x0a, 0x07, 0x45, 0x73, 0x64, 0x65, 0x61, 0x74, 0x68,
	0x12, 0x3f, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x12,
	0x14, 0x2e, 0x65, 0x73, 0x64, 0x65, 0x61, 0x74, 0x68, 0x2e, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d,
	0x73, 0x67, 0x41, 0x64, 0x64, 0x1a, 0x1a, 0x2e, 0x65, 0x73, 0x64, 0x65, 0x61, 0x74, 0x68, 0x2e,
	0x41, 0x64, 0x64, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x42, 0x0a, 0x0c, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73,
	0x67, 0x12, 0x15, 0x2e, 0x65, 0x73, 0x64, 0x65, 0x61, 0x74, 0x68, 0x2e, 0x44, 0x65, 0x6c, 0x61,
	0x79, 0x4d, 0x73, 0x67, 0x50, 0x75, 0x6c, 0x6c, 0x1a, 0x1b, 0x2e, 0x65, 0x73, 0x64, 0x65, 0x61,
	0x74, 0x68, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3f, 0x0a, 0x0b, 0x41, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x61,
	0x79, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x2e, 0x65, 0x73, 0x64, 0x65, 0x61, 0x74, 0x68, 0x2e, 0x44,
	0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x41, 0x63, 0x6b, 0x1a, 0x1a, 0x2e, 0x65, 0x73, 0x64,
	0x65, 0x61, 0x74, 0x68, 0x2e, 0x41, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x48, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x17, 0x2e, 0x65, 0x73, 0x64, 0x65, 0x61,
	0x74, 0x68, 0x2e, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x1a, 0x1d, 0x2e, 0x65, 0x73, 0x64, 0x65, 0x61, 0x74, 0x68, 0x2e, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x36, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x65, 0x73, 0x64, 0x65, 0x61, 0x74, 0x68, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x21, 0x48, 0x01, 0x5a, 0x1d, 0x2e, 0x2f,
	0x65, 0x73, 0x64, 0x65, 0x61, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x65, 0x73,
	0x64, 0x65, 0x61, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData = file_server_proto_rawDesc
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_proto_rawDescData)
	})
	return file_server_proto_rawDescData
}

var file_server_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_server_proto_goTypes = []interface{}{
	(AckStatus)(0),               // 0: esdeath.AckStatus
	(ResultStatus)(0),            // 1: esdeath.ResultStatus
	(Role)(0),                    // 2: esdeath.Role
	(*DelayMsgCancel)(nil),       // 3: esdeath.DelayMsgCancel
	(*DelayMsgAdd)(nil),          // 4: esdeath.DelayMsgAdd
	(*DelayMsgPull)(nil),         // 5: esdeath.DelayMsgPull
	(*DelayMsgAck)(nil),          // 6: esdeath.DelayMsgAck
	(*BaseResult)(nil),           // 7: esdeath.BaseResult
	(*AddDelayMsgResult)(nil),    // 8: esdeath.AddDelayMsgResult
	(*PullDelayMsgResult)(nil),   // 9: esdeath.PullDelayMsgResult
	(*CancelDelayMsgResult)(nil), // 10: esdeath.CancelDelayMsgResult
	(*AckDelayMsgResult)(nil),    // 11: esdeath.AckDelayMsgResult
	(*RoleResult)(nil),           // 12: esdeath.RoleResult
	(*emptypb.Empty)(nil),        // 13: google.protobuf.Empty
}
var file_server_proto_depIdxs = []int32{
	0,  // 0: esdeath.DelayMsgAck.status:type_name -> esdeath.AckStatus
	1,  // 1: esdeath.BaseResult.status:type_name -> esdeath.ResultStatus
	7,  // 2: esdeath.AddDelayMsgResult.baseResult:type_name -> esdeath.BaseResult
	7,  // 3: esdeath.PullDelayMsgResult.baseResult:type_name -> esdeath.BaseResult
	7,  // 4: esdeath.CancelDelayMsgResult.baseResult:type_name -> esdeath.BaseResult
	7,  // 5: esdeath.AckDelayMsgResult.baseResult:type_name -> esdeath.BaseResult
	7,  // 6: esdeath.RoleResult.baseResult:type_name -> esdeath.BaseResult
	2,  // 7: esdeath.RoleResult.role:type_name -> esdeath.Role
	4,  // 8: esdeath.Esdeath.AddDelayMsg:input_type -> esdeath.DelayMsgAdd
	5,  // 9: esdeath.Esdeath.PullDelayMsg:input_type -> esdeath.DelayMsgPull
	6,  // 10: esdeath.Esdeath.AckDelayMsg:input_type -> esdeath.DelayMsgAck
	3,  // 11: esdeath.Esdeath.CancelDelayMsg:input_type -> esdeath.DelayMsgCancel
	13, // 12: esdeath.Esdeath.GetRole:input_type -> google.protobuf.Empty
	8,  // 13: esdeath.Esdeath.AddDelayMsg:output_type -> esdeath.AddDelayMsgResult
	9,  // 14: esdeath.Esdeath.PullDelayMsg:output_type -> esdeath.PullDelayMsgResult
	11, // 15: esdeath.Esdeath.AckDelayMsg:output_type -> esdeath.AckDelayMsgResult
	10, // 16: esdeath.Esdeath.CancelDelayMsg:output_type -> esdeath.CancelDelayMsgResult
	12, // 17: esdeath.Esdeath.GetRole:output_type -> esdeath.RoleResult
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelayMsgCancel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelayMsgAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelayMsgPull); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelayMsgAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDelayMsgResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullDelayMsgResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelDelayMsgResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckDelayMsgResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		EnumInfos:         file_server_proto_enumTypes,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_rawDesc = nil
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
